Init project
k8sp/k8s-users pull request #2
Opened 2017-03-28 09:55 UTC by Yancey1989

* Add `certgen.go` to generate cert files
* Add `policy.go` to update abac policy files
* Use mux for post request router
* Update README.md

TODO:
* Restart APIServer container by [Docker Client](https://github.com/docker/docker/tree/master/client)
* Send email to user.

2017-03-28 10:42 UTC, pineking commented on main.go
> +	"github.com/Yancey1989/k8s-users/users"
是不是直接在 k8sp/k8s-users 下创建 branch 提交 PR？可以避免这种代码交叉？

2017-03-28 10:53 UTC, Yancey1989 commented on main.go
> +	"github.com/Yancey1989/k8s-users/users"
Done.

2017-03-28 11:03 UTC, typhoonzero requested changes

2017-03-28 11:03 UTC, typhoonzero commented on testdata/abac_policy.jsonl
> +{"apiVersion":"abac.authorization.kubernetes.io/v1beta1","kind":"Policy","spec":{"user":"system:serviceaccount:yanxu:default","namespace":"yanxu","resource":"*","apiGroup":"*","readonly":false,"nonRe
这两行yanxu的去掉？用户的策略是需要程序生成的

2017-03-28 11:03 UTC, typhoonzero commented on testdata/users/yanxu/yanxu-crt.pem
> +-----BEGIN RSA PRIVATE KEY-----
这些testdata需要存在么？

2017-03-28 11:03 UTC, typhoonzero commented on users/docker.go
> +package users
这个文件如果没用就先删掉？

2017-03-28 11:03 UTC, typhoonzero commented on users/policy.go
> +
```go
type Policy interface {
  getDefaultServiceAcccount(username string) string
  makePolicy(username, namespace string) Policy
  newPolicy(username, namespace string, policies []Policy) []Policy
  UpdatePolicyFile(username, namespace, policyFile string) error
}
```

2017-03-30 10:08 UTC, zh794390558 commented on users/certgen.go
> +	crt, key := genCerts(caCrt, caKey, username)
key 和 crt 的顺序是否反了?

2017-03-30 10:15 UTC, zh794390558 commented on users/policy.go
> +func getDefaultServiceAcccount(username string) string {
username 应该是 namespace 。

2017-03-30 15:56 UTC, Yancey1989 commented on users/certgen.go
> +	crt, key := genCerts(caCrt, caKey, username)
Thx, done.

2017-03-30 15:56 UTC, Yancey1989 commented on users/policy.go
> +
It seems like `Policy` does not need to be an interface. I add receiver `Exists`, `Append`, `Update` for `Policy`

2017-03-30 15:56 UTC, Yancey1989 commented on testdata/users/yanxu/yanxu-crt.pem
> +-----BEGIN RSA PRIVATE KEY-----
Generate the testdata using `./script/gen_test.sh`.
Done.

2017-03-30 15:56 UTC, Yancey1989 commented on testdata/abac_policy.jsonl
> +{"apiVersion":"abac.authorization.kubernetes.io/v1beta1","kind":"Policy","spec":{"user":"system:serviceaccount:yanxu:default","namespace":"yanxu","resource":"*","apiGroup":"*","readonly":false,"nonRe
Done.

2017-03-30 16:17 UTC, Yancey1989 commented on users/policy.go
> +func getDefaultServiceAcccount(username string) string {
Done.

2017-04-01 02:21 UTC, typhoonzero requested changes

2017-04-01 02:21 UTC, typhoonzero commented on README.md
> +  账号创建后，通过`mail`命令，将欢迎信息以及tls信息发送给用户。
使用说明不需要说明是使用`mail`命令实现的，可以在部署部分说明使用`mail`命令发送邮件，并且要求和邮件服务器之间网络是联通的。

2017-04-01 02:21 UTC, typhoonzero commented on README.md
> +- 增加发送email的流程
已经实现了吧？

2017-04-01 02:21 UTC, typhoonzero commented on makefile
> +test:
文件名应该是`Makefile`

2017-04-01 02:21 UTC, typhoonzero commented on users/certgen.go
> +	certgen.Run("openssl", "x509", "-req", "-in", csr, "-CA", caCrt, "-CAkey",
只是记录下：365天目前是写死的。

2017-04-01 02:21 UTC, typhoonzero commented on users/policy.go
> +func makeRule(username, namespace string) Rule {
一般是 `newRule`或者public函数`NewRule`

2017-04-01 02:21 UTC, typhoonzero commented on users/policy.go
> +func (p *Policy) ToJSONFile(filename string) error {
一般会命名为`DumpJsonFile`之类的

2017-04-01 02:31 UTC, Yancey1989 commented on README.md
> +- 增加发送email的流程
这个PR里还没有，下个PR里会加进来。

2017-04-01 02:31 UTC, Yancey1989 commented on makefile
> +test:
Done.

2017-04-01 02:32 UTC, Yancey1989 commented on users/policy.go
> +func (p *Policy) ToJSONFile(filename string) error {
Done. BTW,  the name `DumpJSONFile` is according with golint.

2017-04-01 07:46 UTC, typhoonzero approved these changes
LGTM

2017-04-01 08:56 UTC, merged